### PR TITLE
Added Url Recogniser and Client Checker

### PR DESCRIPTION
**Pull request by rohithvegesna**
Now url's posted in blog will be recognised. A new option was added for
Executive Body members to check client status

### CODE REVIEW

**Comment by ShootingKing-AM** [comment]
Where is checksearch.php implemented ? Is it a To-Do ? Also in earlier pull req #9 you have proposed some redirection bug fixes, where are those ?

**Comment by rohithvegesna** [comment]
Those bugs are in signup.php and updateprofile.php

**Comment by ShootingKing-AM** [comment]
Fix them and commit to your urlblog branch.

**Comment by rohithvegesna** [comment]
They were already fixed

**Comment by ShootingKing-AM** [comment]
Oh! confusing pull #9 xD

**Pull request merged**
